version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ums-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ums
      MYSQL_ROOT_PASSWORD: postgres
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql